INSERT INTO public.showcase_items (user_id, type, status, title, description, content, category_tags)
VALUES (
  '82f10958-6619-40fb-ae37-452bbe3b2891',
  'guidebook',
  'pending',
  'What is Vibe Coding? A Guide for AI-First Builders',
  'A practical guide to vibe coding: what it is, how AI-assisted building fits into professional pipelines, and how the <Good Vibes Café/> collective uses it to ship faster.',
  E'## What is vibe coding?\n\nVibe coding is the practice of building software by describing intent in natural language and letting an AI partner draft, refactor and ship the code. You stay in the driver seat: setting direction, reviewing diffs, owning the architecture. The AI handles the keystrokes.\n\nThe term spread in 2025 as tools like Lovable, Cursor and Claude Code made it realistic to assemble production apps from a series of conversations instead of line-by-line typing.\n\n## Why builders care\n\n- **Speed.** A weekend prototype now ships in an evening. A landing page in minutes.\n- **Lower friction.** Designers, founders and operators can ship working software without a full engineering hire.\n- **Tighter loops.** Idea, build, test, learn, compressed into a single sitting.\n\n## How it fits a professional pipeline\n\nVibe coding does not replace engineering rigour. It changes where the rigour lives:\n\n1. **Intent first.** Write a clear brief. The clearer the prompt, the cleaner the diff.\n2. **Small steps.** Ship one capability at a time. Review every change.\n3. **Tests and types.** Keep the safety net the AI can lean on.\n4. **Human review at the seams.** Auth, payments, data models, anything user-facing, read the code.\n5. **Observability.** Logs, errors, analytics. Know what shipped is actually doing.\n\n## Where the collective comes in\n\n<Good Vibes Café/> is a collective of builders, strategists and connectors who vibe code in the open. We share what worked, what broke, and the playbooks behind it.\n\n- Browse the **Showcase** for case studies, tools and sample code from members.\n- Drop into the **Forum** to ask, swap prompts and find collaborators.\n- Join an **Event** to pair up on a build or watch a teardown live.\n\n## Start vibing\n\n1. Pick one small problem worth solving.\n2. Open your AI builder and describe the first slice.\n3. Ship it. Share it in the Forum. Iterate.\n\nThat is the whole loop. Welcome to the café.',
  ARRAY['vibe coding','ai builders','guide','getting started']
);